# -*- coding: utf-8 -*-
"""Data Preparation for Project Business Analyst- Conversion Rate Optimization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1i1dTZuyInuziV1Ux97dj1YC1UMdEAq
"""

import pandas as pd

path_database = "/content/Project Business Analytics- Conversion Rate Optimization - KAG_conversion_data.csv.csv"
df = pd.read_csv(path_database)

df.head (10)

df.isna().sum()

df.duplicated().sum()

df.info()